// DO NOT EDIT. This file is generated by Fresh.
// This file SHOULD be checked into source version control.
// This file is automatically updated during development when running `dev.ts`.

import * as $0 from "./routes/_404.tsx";
import * as $1 from "./routes/_app.tsx";
import * as $2 from "./routes/aboutMe/index.tsx";
import * as $3 from "./routes/api/like.ts";
import * as $4 from "./routes/article/[url_title].tsx";
import * as $5 from "./routes/index.tsx";
import * as $6 from "./routes/test/index.tsx";
import * as $$0 from "./islands/Comments.tsx";
import * as $$1 from "./islands/Counter.tsx";
import * as $$2 from "./islands/LikeArticle.tsx";

const manifest = {
  routes: {
    "./routes/_404.tsx": $0,
    "./routes/_app.tsx": $1,
    "./routes/aboutMe/index.tsx": $2,
    "./routes/api/like.ts": $3,
    "./routes/article/[url_title].tsx": $4,
    "./routes/index.tsx": $5,
    "./routes/test/index.tsx": $6,
  },
  islands: {
    "./islands/Comments.tsx": $$0,
    "./islands/Counter.tsx": $$1,
    "./islands/LikeArticle.tsx": $$2,
  },
  baseUrl: import.meta.url,
};

export default manifest;
